NAME: 'EMA Crossover'
MODULE: 'ema_crossover'
CLASS: 'EMAcrossOver'
INTERVAL: '1h'
PERIOD: 300
RISK_PC: 5
SIZING: 'risk'
PARAMETERS:
  slow_ema: 100
  fast_ema: 50
  RR: 2.0

# Define pairs to monitor
WATCHLIST: ['RELIANCE-EQ', 'WIPRO-EQ', 'ZEEL-EQ', 'INFY-EQ', 'ADANIENT-EQ', 'BEL-EQ', 'BHEL-EQ', 'GMRINFRA-EQ']