OANDA:
  LIVE_API: "api-fxtrade.oanda.com"
  LIVE_ACCESS_TOKEN: "12345678900987654321-abc34135acde13f13530"
  PRACTICE_API: "api-fxpractice.oanda.com"
  PRACTICE_ACCESS_TOKEN: "12345678900987654321-abc34135acde13f13530"
  DEFAULT_ACCOUNT_ID: "xxx-xxx-xxxxxxxx-001"
  PORT: 443

CCXT:EXCHANGE:
  api_key: "xxxx"
  secret: "xxxx"
  base_currency: "USDT"

dYdX:
  ETH_ADDRESS: "0xxxxx"
  ETH_PRIV_KEY: "xxxxx"

finvasia:
  #provide the TOTP key for your account for Auto-Login process
  TOTP_KEY: "L5D7ABHZH2XG7BB4MQ5EG632GRK3P66H"
  TOTP_INTERVAL: 30
  #your API Key obtained from Shoonya/Finvasia
  API_KEY: ""
  USER_NAME: ""
  PASSWORD: ""